#!/usr/bin/env python
Import('env_geomtools')
import os

source_dirs = [
    "boolean",
    "boolean/clipper6",
    "boolean/clipper10",
    "offset",
    "decomp",
    "utils",
]
sources = [Glob(d + "/" + "*.cpp") for d in source_dirs]
env_geomtools.add_source_files(env_geomtools.modules_sources, sources)
