#!/usr/bin/env python
Import('env_geomtools')
import os

source_dirs = [
    # Boolean
    "boolean",
    "boolean/clipper6",
    "boolean/clipper10",
    # Offset
    "offset",
    "offset/clipper6",
    "offset/clipper10",
    # Decomp
    "decomp",
    "decomp/builtin",
    "decomp/clipper10",
    # Other
    "utils",
]
sources = [Glob(d + "/" + "*.cpp") for d in source_dirs]
env_geomtools.add_source_files(env_geomtools.modules_sources, sources)
