os: Visual Studio 2019

platform: x64

environment:
  HOME: "%HOMEDRIVE%%HOMEPATH%"
  PYTHON: C:\Python38
  SCONS_CACHE_ROOT: "%HOME%\\scons_cache"
  SCONS_CACHE_LIMIT: 1024
  MODULES_DISABLED: misc\ci\modules_disabled.txt
  GODOT_REPO_URL: "https://github.com/godotengine/godot"
  matrix:
    - GD_PLATFORM: windows
      TOOLS: yes
      TARGET: release_debug

cache:
  - "%SCONS_CACHE_ROOT%"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install scons==3.1.2

before_build:
  # Get Godot source and install the module
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - git clone --depth=1 %GODOT_REPO_URL% -b 3.2 --single-branch
  - cd godot
  - mklink /d modules\geomtools %APPVEYOR_BUILD_FOLDER%

  - echo %GD_PLATFORM%
  - python --version
  - scons --version
  - SET "SCONS_CACHE=%SCONS_CACHE_ROOT%\%APPVEYOR_REPO_BRANCH%"
  - ps: $env:MODULES_DISABLED = $($env:APPVEYOR_BUILD_FOLDER + "\" + $env:MODULES_DISABLED)

build_script:
  - ps: scons platform=%GD_PLATFORM% target=%TARGET% tools=%TOOLS% debug_symbols=no verbose=yes progress=no gdnative_wrapper=yes $(type $env:MODULES_DISABLED)
