#!/usr/bin/env python
Import('env')

env_geomtools = env.Clone()

env_geomtools.add_source_files(env.modules_sources, '*.cpp')

Export('env_geomtools')

SConscript('2d/SCsub')

if not env["disable_3d"]:
    SConscript('3d/SCsub')
