#!/usr/bin/env python
Import('env')
env_geomtools = env.Clone()

thirdparty_dirs = [
    "thirdparty/clipper/"
]
env_thirdparty = env_geomtools.Clone()
for d in thirdparty_dirs:
    env_thirdparty.add_source_files(env.modules_sources, d + '*.cpp')
env_thirdparty.disable_warnings()

env_geomtools.Prepend(CPPDEFINES={"GEOMETRY_TOOLS_SCALE_FACTOR" : env_geomtools["geomtools_scale_factor"]})

env_geomtools.add_source_files(env.modules_sources, '*.cpp')

Export('env_geomtools')

SConscript('2d/SCsub')

if not env["disable_3d"]:
    SConscript('3d/SCsub')
