#!/usr/bin/env python
Import('env_geomtools')

env_geomtools.add_source_files(env_geomtools.modules_sources, '*.cpp')
env_geomtools.add_source_files(env_geomtools.modules_sources, 'bind/*.cpp')

Export('env_geomtools')

SConscript('polytools/SCsub')
